### ISSUE TITLE
Crypto has been deprecated

### ISSUE THREAD

**Issue by yenche123** [juanelas/paillier-js#3]
Hi,
    The project is required to use package  "crypto". However, it has been deprecated from npm official website. Thus, I can not install it via `npm install crypto`.

![image](https://user-images.githubusercontent.com/28533125/78689580-115aba00-7929-11ea-9f10-ab682deeb6d2.png)

    Do you have any solution?

**Comment by shanecurran** [comment]
You don't need to run `npm install crypto`. It's built into Node.js, so simply having `require('crypto')` in your source code should be enough.

**Comment by yenche123** [comment]
@shanecurran 
The code does not run on the server. It needs to run on the terminal devices (Wechat mini-program); however, the environment does not have the module.
I need encrypt data on the layer of terminal devices to ensure that the source data must not be known by the servers, which offer the computing power.

**Comment by juanelas** [comment]
As @shanecurran explained, you don't need to install crypto, since it is specific to Node.js. If you plan to use it with native JS, you may want to give a try to paillier-bigint package, which uses esnext native implementation of bigints; although not sure if wechat mini-program will allow esnext features.
